// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: score_boss_settle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from score_boss_settle.proto</summary>
  public static partial class ScoreBossSettleReflection {

    #region Descriptor
    /// <summary>File descriptor for score_boss_settle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ScoreBossSettleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdzY29yZV9ib3NzX3NldHRsZS5wcm90bxIFcHJvdG8aDHB1YmxpYy5wcm90",
            "bxofdHJhdmVsZXJfZHVlbF9yYW5rX3VwbG9hZC5wcm90byK7AQoSU2NvcmVC",
            "b3NzU2V0dGxlUmVxEgwKBFN0YXIYASABKA0SDQoFU2NvcmUYAiABKA0SMAoG",
            "c2FtcGxlGAMgASgLMiAucHJvdG8uVHJhdmVsZXJEdWVsQmF0dGxlU2FtcGxl",
            "cxITCgtEYW1hZ2VTY29yZRgEIAEoDRISCgpTa2lsbFNjb3JlGAUgASgNEhcK",
            "D0Jvc3NSZXN1bHRMZXZlbBgGIAEoDRIUCgtOZXh0UGFja2FnZRj/DyABKAwi",
            "XAoTU2NvcmVCb3NzU2V0dGxlUmVzcBINCgV0b2tlbhgBIAEoCRIPCgdvbGRS",
            "YW5rGAIgASgNEg8KB25ld1JhbmsYAyABKA0SFAoLTmV4dFBhY2thZ2UY/w8g",
            "ASgMUABQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.PublicReflection.Descriptor, global::Proto.TravelerDuelRankUploadReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ScoreBossSettleReq), global::Proto.ScoreBossSettleReq.Parser, new[]{ "Star", "Score", "Sample", "DamageScore", "SkillScore", "BossResultLevel", "NextPackage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ScoreBossSettleResp), global::Proto.ScoreBossSettleResp.Parser, new[]{ "Token", "OldRank", "NewRank", "NextPackage" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ScoreBossSettleReq : pb::IMessage<ScoreBossSettleReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ScoreBossSettleReq> _parser = new pb::MessageParser<ScoreBossSettleReq>(() => new ScoreBossSettleReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ScoreBossSettleReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ScoreBossSettleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScoreBossSettleReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScoreBossSettleReq(ScoreBossSettleReq other) : this() {
      star_ = other.star_;
      score_ = other.score_;
      sample_ = other.sample_ != null ? other.sample_.Clone() : null;
      damageScore_ = other.damageScore_;
      skillScore_ = other.skillScore_;
      bossResultLevel_ = other.bossResultLevel_;
      nextPackage_ = other.nextPackage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScoreBossSettleReq Clone() {
      return new ScoreBossSettleReq(this);
    }

    /// <summary>Field number for the "Star" field.</summary>
    public const int StarFieldNumber = 1;
    private uint star_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Star {
      get { return star_; }
      set {
        star_ = value;
      }
    }

    /// <summary>Field number for the "Score" field.</summary>
    public const int ScoreFieldNumber = 2;
    private uint score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    /// <summary>Field number for the "sample" field.</summary>
    public const int SampleFieldNumber = 3;
    private global::Proto.TravelerDuelBattleSamples sample_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.TravelerDuelBattleSamples Sample {
      get { return sample_; }
      set {
        sample_ = value;
      }
    }

    /// <summary>Field number for the "DamageScore" field.</summary>
    public const int DamageScoreFieldNumber = 4;
    private uint damageScore_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DamageScore {
      get { return damageScore_; }
      set {
        damageScore_ = value;
      }
    }

    /// <summary>Field number for the "SkillScore" field.</summary>
    public const int SkillScoreFieldNumber = 5;
    private uint skillScore_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SkillScore {
      get { return skillScore_; }
      set {
        skillScore_ = value;
      }
    }

    /// <summary>Field number for the "BossResultLevel" field.</summary>
    public const int BossResultLevelFieldNumber = 6;
    private uint bossResultLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BossResultLevel {
      get { return bossResultLevel_; }
      set {
        bossResultLevel_ = value;
      }
    }

    /// <summary>Field number for the "NextPackage" field.</summary>
    public const int NextPackageFieldNumber = 2047;
    private pb::ByteString nextPackage_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString NextPackage {
      get { return nextPackage_; }
      set {
        nextPackage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ScoreBossSettleReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ScoreBossSettleReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Star != other.Star) return false;
      if (Score != other.Score) return false;
      if (!object.Equals(Sample, other.Sample)) return false;
      if (DamageScore != other.DamageScore) return false;
      if (SkillScore != other.SkillScore) return false;
      if (BossResultLevel != other.BossResultLevel) return false;
      if (NextPackage != other.NextPackage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Star != 0) hash ^= Star.GetHashCode();
      if (Score != 0) hash ^= Score.GetHashCode();
      if (sample_ != null) hash ^= Sample.GetHashCode();
      if (DamageScore != 0) hash ^= DamageScore.GetHashCode();
      if (SkillScore != 0) hash ^= SkillScore.GetHashCode();
      if (BossResultLevel != 0) hash ^= BossResultLevel.GetHashCode();
      if (NextPackage.Length != 0) hash ^= NextPackage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Star != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Star);
      }
      if (Score != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Score);
      }
      if (sample_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Sample);
      }
      if (DamageScore != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(DamageScore);
      }
      if (SkillScore != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(SkillScore);
      }
      if (BossResultLevel != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(BossResultLevel);
      }
      if (NextPackage.Length != 0) {
        output.WriteRawTag(250, 127);
        output.WriteBytes(NextPackage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Star != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Star);
      }
      if (Score != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Score);
      }
      if (sample_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Sample);
      }
      if (DamageScore != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(DamageScore);
      }
      if (SkillScore != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(SkillScore);
      }
      if (BossResultLevel != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(BossResultLevel);
      }
      if (NextPackage.Length != 0) {
        output.WriteRawTag(250, 127);
        output.WriteBytes(NextPackage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Star != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Star);
      }
      if (Score != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Score);
      }
      if (sample_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sample);
      }
      if (DamageScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DamageScore);
      }
      if (SkillScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SkillScore);
      }
      if (BossResultLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BossResultLevel);
      }
      if (NextPackage.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(NextPackage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ScoreBossSettleReq other) {
      if (other == null) {
        return;
      }
      if (other.Star != 0) {
        Star = other.Star;
      }
      if (other.Score != 0) {
        Score = other.Score;
      }
      if (other.sample_ != null) {
        if (sample_ == null) {
          Sample = new global::Proto.TravelerDuelBattleSamples();
        }
        Sample.MergeFrom(other.Sample);
      }
      if (other.DamageScore != 0) {
        DamageScore = other.DamageScore;
      }
      if (other.SkillScore != 0) {
        SkillScore = other.SkillScore;
      }
      if (other.BossResultLevel != 0) {
        BossResultLevel = other.BossResultLevel;
      }
      if (other.NextPackage.Length != 0) {
        NextPackage = other.NextPackage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Star = input.ReadUInt32();
            break;
          }
          case 16: {
            Score = input.ReadUInt32();
            break;
          }
          case 26: {
            if (sample_ == null) {
              Sample = new global::Proto.TravelerDuelBattleSamples();
            }
            input.ReadMessage(Sample);
            break;
          }
          case 32: {
            DamageScore = input.ReadUInt32();
            break;
          }
          case 40: {
            SkillScore = input.ReadUInt32();
            break;
          }
          case 48: {
            BossResultLevel = input.ReadUInt32();
            break;
          }
          case 16378: {
            NextPackage = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Star = input.ReadUInt32();
            break;
          }
          case 16: {
            Score = input.ReadUInt32();
            break;
          }
          case 26: {
            if (sample_ == null) {
              Sample = new global::Proto.TravelerDuelBattleSamples();
            }
            input.ReadMessage(Sample);
            break;
          }
          case 32: {
            DamageScore = input.ReadUInt32();
            break;
          }
          case 40: {
            SkillScore = input.ReadUInt32();
            break;
          }
          case 48: {
            BossResultLevel = input.ReadUInt32();
            break;
          }
          case 16378: {
            NextPackage = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ScoreBossSettleResp : pb::IMessage<ScoreBossSettleResp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ScoreBossSettleResp> _parser = new pb::MessageParser<ScoreBossSettleResp>(() => new ScoreBossSettleResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ScoreBossSettleResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.ScoreBossSettleReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScoreBossSettleResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScoreBossSettleResp(ScoreBossSettleResp other) : this() {
      token_ = other.token_;
      oldRank_ = other.oldRank_;
      newRank_ = other.newRank_;
      nextPackage_ = other.nextPackage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ScoreBossSettleResp Clone() {
      return new ScoreBossSettleResp(this);
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 1;
    private string token_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oldRank" field.</summary>
    public const int OldRankFieldNumber = 2;
    private uint oldRank_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint OldRank {
      get { return oldRank_; }
      set {
        oldRank_ = value;
      }
    }

    /// <summary>Field number for the "newRank" field.</summary>
    public const int NewRankFieldNumber = 3;
    private uint newRank_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NewRank {
      get { return newRank_; }
      set {
        newRank_ = value;
      }
    }

    /// <summary>Field number for the "NextPackage" field.</summary>
    public const int NextPackageFieldNumber = 2047;
    private pb::ByteString nextPackage_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString NextPackage {
      get { return nextPackage_; }
      set {
        nextPackage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ScoreBossSettleResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ScoreBossSettleResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Token != other.Token) return false;
      if (OldRank != other.OldRank) return false;
      if (NewRank != other.NewRank) return false;
      if (NextPackage != other.NextPackage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (OldRank != 0) hash ^= OldRank.GetHashCode();
      if (NewRank != 0) hash ^= NewRank.GetHashCode();
      if (NextPackage.Length != 0) hash ^= NextPackage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (OldRank != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(OldRank);
      }
      if (NewRank != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(NewRank);
      }
      if (NextPackage.Length != 0) {
        output.WriteRawTag(250, 127);
        output.WriteBytes(NextPackage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Token.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Token);
      }
      if (OldRank != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(OldRank);
      }
      if (NewRank != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(NewRank);
      }
      if (NextPackage.Length != 0) {
        output.WriteRawTag(250, 127);
        output.WriteBytes(NextPackage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (OldRank != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OldRank);
      }
      if (NewRank != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NewRank);
      }
      if (NextPackage.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(NextPackage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ScoreBossSettleResp other) {
      if (other == null) {
        return;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.OldRank != 0) {
        OldRank = other.OldRank;
      }
      if (other.NewRank != 0) {
        NewRank = other.NewRank;
      }
      if (other.NextPackage.Length != 0) {
        NextPackage = other.NextPackage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
          case 16: {
            OldRank = input.ReadUInt32();
            break;
          }
          case 24: {
            NewRank = input.ReadUInt32();
            break;
          }
          case 16378: {
            NextPackage = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Token = input.ReadString();
            break;
          }
          case 16: {
            OldRank = input.ReadUInt32();
            break;
          }
          case 24: {
            NewRank = input.ReadUInt32();
            break;
          }
          case 16378: {
            NextPackage = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
