// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: vampire_survivor_extra_reward_select.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from vampire_survivor_extra_reward_select.proto</summary>
  public static partial class VampireSurvivorExtraRewardSelectReflection {

    #region Descriptor
    /// <summary>File descriptor for vampire_survivor_extra_reward_select.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VampireSurvivorExtraRewardSelectReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cip2YW1waXJlX3N1cnZpdm9yX2V4dHJhX3Jld2FyZF9zZWxlY3QucHJvdG8S",
            "BXByb3RvGiR2YW1waXJlX3N1cnZpdm9yX3Jld2FyZF9zZWxlY3QucHJvdG9Q",
            "AGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.VampireSurvivorRewardSelectReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
